# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Vagrant by HashiCorp
# https://www.vagrantup.com/
#
# Vagrantfile Explained: Setting Up and Provisioning with Shell
# https://www.sitepoint.com/vagrantfile-explained-setting-provisioning-shell/

# Vagrant uses API versions for its configuration file. This is how it can stay backwards
# compatible. So in every Vagrantfile we need to specify which version to use. The current one is
# version 2 which works with Vagrant 1.1 and up.
#
Vagrant.configure("2") do |config|
    # For a complete reference, please see the online documentation at https://docs.vagrantup.com.

    # Every Vagrant development environment requires a box. You can search for boxes at
    # https://vagrantcloud.com/search.
    #
    # $ vagrant init hashicorp/bionic64
    #
    config.vm.box = "hashicorp/bionic64"
end
