" Use indentation scripts located in the indent folder of your VIM installation.
if has("autocmd")
  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
"  filetype plugin indent on
endif

" Turn on color syntax highlighting.
syntax on

" Show whitespace.
set list
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

" Enable spell check.
set spell spelllang=en_us
hi clear SpellBad
hi SpellBad cterm=underline

" Enable line numbers.
set number

" set autoindent
set tabstop=4
set shiftwidth=4
set expandtab

" Highlight all search matches.
set hlsearch
hi MatchParen cterm=underline ctermbg=Black ctermfg=Red

" Press F4 to toggle highlighting on/off, and show current value.
:noremap <F4> :set hlsearch! hlsearch?<CR>

" Press return to temporarily get out of the highlighted search.
:nnoremap <CR> :nohlsearch<CR><CR>

" Put swap, backup and undo files in a special location instead of the working directory of the
" file being edited
set backup
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//
set writebackup

" Look in directory containing current file (.),
" then current directory (empty text between two commas),
" then each directory under current directory ('**').
:set path=.,,**

" Use Tab and Shift+Tab to go to next and previous tabs.
:nnoremap <Tab> :tabn<CR>
:nnoremap <S-Tab> :tabp<CR>

