" Show whitespace.
set list
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

" Enable spell check.
set spell spelllang=en_us
hi clear SpellBad
hi SpellBad cterm=underline

" Enable line numbers.
set number

set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
