// ***********************************************************************
// *                                                                     *
// *                      PCS100 Network Supervisor                      *
// *                                                                     *
// *       Copyright (c) 1987-1991  Vorne Industries Incorporated.       *
// *                         All rights reserved.                        *
// *                                                                     *
// ***********************************************************************

void	HelpDo(short item);
void	HelpInit(void);
void	LanguageDo(short item);
void	LanguageInit(void);
void	PrefsDo(short item);
void	PrefsInit(void);
void	PrefsInitData(void);
